name: Build

on:
  pull_request:
    branches: [main]

jobs:
  operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make

  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: make docker-build-ui
