name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: |
          go mod tidy
          make test

  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .versions/bun

      - run: |
          bun install --cwd packages/ui --frozen-lockfile
          make test-ui
